### ISSUE TITLE
Unsatisfied constraint: 'Import-Package: com.ibm.icu.text; version="3.8.1"'

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse/gef-classic#90]
Follow up on https://github.com/eclipse-platform/eclipse.platform.releng/issues/69

Import GEF sources into 4.25 SDK and enjoy compilation errors `Unsatisfied constraint: 'Import-Package: com.ibm.icu.text; version="3.8.1"'`
Also GEF can't work anymore on plain 4.25 SDK without installing extra `com.ibm.icu` bundle from orbit.
Root cause is that few GEF bundles expect **versioned** `com.ibm.icu.text` package to exist in the installation, but 4.25 SDK brings only plain maven artifact without proper package metadata.

The fix is trivial, I will push the PR in a moment.

**Comment by iloveeclipse** [comment]
@vogella : what is needed to get new GEF nigtly build now?

**Comment by vogella** [comment]
> @vogella : what is needed to get new GEF nigtly build now?

See https://github.com/eclipse/gef-classic for the update site. The build job checks every 5 min for changes and publish the latest update side.

**Comment by vogella** [comment]
https://github.com/eclipse/gef-classic/pull/89 may also be needed in case you use also GMF. We waiting for @[pcdavid](https://github.com/pcdavid) to check if this fixes GMF which got broken by https://github.com/eclipse/gef-classic/pull/81

**Comment by iloveeclipse** [comment]
Thanks. Is there somewhere a zipped update site for offline installation?

**Comment by vogella** [comment]
> Thanks. Is there somewhere a zipped update site for offline installation? Sure, wget will also work, just curious if there is one actually.

I don't think there is. 

I'm now back to my vacation, enough Eclipse discussions / work for a vacation day

**Comment by azoitl** [comment]
> Thanks. Is there somewhere a zipped update site for offline installation? Sure, wget will also work, just curious if there is one actually.
Any tips on how to create such zips as part of a build job? My experience is mostly in RCP developement and there we always package full product zips and no p2 zips.

**Comment by iloveeclipse** [comment]
If the build job runs on Linux, it can use "zip" command that can recursively put p2 site to a zip file, something like "zip -r repository.zip /path/to/p2/repo". I have no access to the shell right now, but that should be very straightforward.

**Comment by cdietrich** [comment]
Tacho builds a repository zip right next to the repository folder that is currently archived so that just needs to be put somewhere. Maybe adapt 
https://github.com/eclipse/gef-classic/blob/c1174994ef30133c0ee1e18bd39a6fa433aa7833/Jenkinsfile#L30 As a first and 
https://github.com/eclipse/gef-classic/blob/c1174994ef30133c0ee1e18bd39a6fa433aa7833/Jenkinsfile#L39 As a second step
